/**
 * read_infer.cu - Load TimingPredict inference results and update GPU timing arrays
 *
 * Reads .infer CSV files generated by inference.py and updates GPUTimer's pinSlew
 * and arcDelay arrays with ML-predicted slew and delay values.
 *
 * File format (from inference.py):
 *   # Node predictions (pin_id-based)
 *   node_id,slew_er,slew_ef,slew_lr,slew_lf,net_delay_er,net_delay_ef,net_delay_lr,net_delay_lf
 *   0,0.049687,0.049687,0.049687,0.049687,0.000400,0.000400,0.000400,0.000400
 *   ...
 *
 *   # Cell edge predictions (from_pin_id to to_pin_id)
 *   from_pin_id,to_pin_id,cell_delay_er,cell_delay_ef,cell_delay_lr,cell_delay_lf
 *   10,20,0.123,0.134,0.234,0.245
 *   ...
 *
 * Arc lookup uses CSR format via pin_forward_arc_list to find actual arc_id from (from_pin_id, to_pin_id).
 */

#include "GPUTimer.h"
#include "gputimer/db/GTDatabase.h"
#include "common/utils/log.h"
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <array>
#include <unordered_map>
#include <limits>

namespace gt {

// Helper: trim whitespace from string
static std::string trim(const std::string& str) {
    size_t first = str.find_first_not_of(" \t\r\n");
    if (first == std::string::npos) return "";
    size_t last = str.find_last_not_of(" \t\r\n");
    return str.substr(first, last - first + 1);
}

// Helper: parse CSV line into float vector
static bool parse_csv_line(const std::string& line, std::vector<float>& values) {
    std::istringstream iss(line);
    std::string token;
    values.clear();

    while (std::getline(iss, token, ',')) {
        token = trim(token);
        if (token.empty()) continue;
        try {
            values.push_back(std::stof(token));
        } catch (...) {
            return false;  // Parse error
        }
    }
    return !values.empty();
}

// Helper: split CSV line into string tokens (used when a field is a string, not a float)
static std::vector<std::string> split_csv_str(const std::string& line) {
    std::vector<std::string> tokens;
    std::istringstream iss(line);
    std::string token;
    while (std::getline(iss, token, ','))
        tokens.push_back(trim(token));
    return tokens;
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared GPU update: D2H → apply slew / net-delay / cell-delay updates → H2D
// Called by both read_infer() and read_opr_gt_infer() after their respective
// parsers have built the three data vectors (all indexed by GPUTimer pin IDs).
// ─────────────────────────────────────────────────────────────────────────────
void GPUTimer::apply_infer_data(
    const std::vector<std::pair<int, std::array<float, 4>>>& slews,
    const std::vector<std::pair<int, std::array<float, 4>>>& net_delays,
    const std::vector<std::tuple<int, int, std::array<float, 4>>>& cell_delays,
    float time_to_internal)
{
    int num_arcs = static_cast<int>(gtdb.timing_arc_from_pin_id.size());
    logger.info("[apply_infer_data] num_arcs=%d\n", num_arcs);

    // Ensure any previous GPU kernels have completed before copying
    cudaDeviceSynchronize();
    logger.info("[apply_infer_data] GPU synchronized before D2H copy\n");

    // Copy arcDelay to host for modification
    float* h_arcDelay = new float[num_arcs * 8];
    cudaMemcpy(h_arcDelay, arcDelay, num_arcs * 8 * sizeof(float), cudaMemcpyDeviceToHost);
    logger.info("[apply_infer_data] Copied arcDelay D2H: %d arcs * 8 * 4 bytes\n", num_arcs);

    // Copy pinSlew to host for modification (pinSlew is pinSlew GPU array)
    // pinSlew layout: pinSlew[pin_id * NUM_ATTR + corner] where NUM_ATTR = 4
    int num_pins = static_cast<int>(gtdb.pin_names.size());
    float* h_pinSlew = new float[num_pins * 4];
    cudaMemcpy(h_pinSlew, pinSlew, num_pins * 4 * sizeof(float), cudaMemcpyDeviceToHost);
    logger.info("[apply_infer_data] Copied pinSlew D2H: %d pins * 4 corners * 4 bytes\n", num_pins);

    // Ensure D2H copy is complete before modifying on host
    cudaDeviceSynchronize();
    logger.info("[apply_infer_data] GPU synchronized after D2H copy\n");

    // Update slew values for pins
    int slew_count = 0;
    for (const auto& [pin_id, slew] : slews) {
        if (pin_id >= 0 && pin_id < num_pins) {
            const char* pin_name = (pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[pin_id].c_str() : "UNKNOWN";
            for (int corner = 0; corner < 4; corner++) {
                float slew_internal = slew[corner] * time_to_internal;
                h_pinSlew[pin_id * 4 + corner] = slew_internal;
                if (slew_count < 3) {
                    logger.info("[apply_infer_data]   pin[%d] '%s' slew[%d] = %.6e ns -> %.6e internal\n",
                        pin_id, pin_name, corner, slew[corner], slew_internal);
                }
            }
            slew_count++;
        }
    }
    logger.info("[apply_infer_data] Updated %d pins with slew values\n", slew_count);

    // Update net delays
    // For each net delay prediction (indexed by pin_id), find fanin net arcs using CSR lookup
    int net_delay_updates = 0;
    int net_delay_missing = 0;
    for (const auto& [pin_id, delays] : net_delays) {
        // Use pin_backward_arc_list with CSR format for efficient fanin lookup
        int arc_start = gtdb.pin_backward_arc_list_end[pin_id];
        int arc_end = (pin_id + 1 < (int)gtdb.pin_backward_arc_list_end.size())
                      ? gtdb.pin_backward_arc_list_end[pin_id + 1]
                      : (int)gtdb.pin_backward_arc_list.size();

        bool found = false;
        for (int i = arc_start; i < arc_end; i++) {
            int arc_id = gtdb.pin_backward_arc_list[i];
            if (gtdb.arc_types[arc_id] != 0) continue;  // Skip non-net arcs

            found = true;
            // Found net arc driving this pin - update only valid indices {0, 3, 4, 7}
            // For net arcs, input and output transitions must match (rise→rise or fall→fall)
            // Invalid transitions (rise→fall, fall→rise) are indices {1,2,5,6} - left as NaN
            float delay0 = delays[0] * time_to_internal;  // er (rise)
            float delay1 = delays[1] * time_to_internal;  // ef (fall)
            float delay2 = delays[2] * time_to_internal;  // lr (rise)
            float delay3 = delays[3] * time_to_internal;  // lf (fall)
            h_arcDelay[arc_id * 8 + 0] = delay0;  // i=0: rise-to-rise (valid)
            h_arcDelay[arc_id * 8 + 3] = delay1;  // i=3: fall-to-fall (valid)
            h_arcDelay[arc_id * 8 + 4] = delay2;  // i=4: rise-to-rise (valid)
            h_arcDelay[arc_id * 8 + 7] = delay3;  // i=7: fall-to-fall (valid)
            // Indices [1,2,5,6] remain NaN (invalid transitions for net arcs)

            if (net_delay_updates < 3) {
                const char* pin_name = (pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[pin_id].c_str() : "UNKNOWN";
                logger.info("[apply_infer_data] Net delay pin[%d] '%s' -> arc %d: [%.6e,%.6e,%.6e,%.6e] internal\n",
                    pin_id, pin_name, arc_id, delay0, delay1, delay2, delay3);
            }
            net_delay_updates++;
        }
        if (!found) net_delay_missing++;
    }
    logger.info("[apply_infer_data] Updated %d net arcs, %d net delays with no fanin arc\n", net_delay_updates, net_delay_missing);

    // Update cell delays
    // For each cell delay prediction, find the arc by traversing forward arcs
    int cell_delay_updates = 0;
    int cell_delay_missing = 0;
    for (const auto& [from_pin_id, to_pin_id, delays] : cell_delays) {
        // Iterate through forward arcs of from_pin_id using CSR format
        int arc_start = gtdb.pin_forward_arc_list_end[from_pin_id];
        int arc_end = (from_pin_id + 1 < (int)gtdb.pin_forward_arc_list_end.size())
                      ? gtdb.pin_forward_arc_list_end[from_pin_id + 1]
                      : (int)gtdb.pin_forward_arc_list.size();

        bool found = false;
        int num_fanout = arc_end - arc_start;

        for (int i = arc_start; i < arc_end; i++) {
            int arc_id = gtdb.pin_forward_arc_list[i];

            // Check if this arc connects to to_pin_id and is a cell arc
            if (gtdb.timing_arc_to_pin_id[arc_id] != to_pin_id) continue;
            if (gtdb.arc_types[arc_id] != 1) continue;  // Must be cell arc

            found = true;

            // CSV corners: [er, ef, lr, lf] = [(el=0,orf=0), (el=0,orf=1), (el=1,orf=0), (el=1,orf=1)]
            std::array<std::pair<int, int>, 4> el_orf = {{{0, 0}, {0, 1}, {1, 0}, {1, 1}}};

            int corners_updated = 0;
            for (int corner = 0; corner < 4; corner++) {
                int el = el_orf[corner].first;
                int orf = el_orf[corner].second;

                // Check if this timing is valid
                if (gtdb.timing_arc_id_map[arc_id * 2 + el] == -1) continue;

                float corner_value = delays[corner] * time_to_internal;

                // Update all indices i (0-7) where (i >> 2) == el && (((i & 4) >> 1) + (i & 1)) & 1 == orf
                for (int i = 0; i < 8; i++) {
                    int i_el = i >> 2;
                    int i_tel_rf = ((i & 0b100) >> 1) + (i & 1);
                    int i_orf = i_tel_rf & 1;

                    if (i_el == el && i_orf == orf) {
                        h_arcDelay[arc_id * 8 + i] = corner_value;
                        corners_updated++;
                    }
                }
            }

            if (cell_delay_updates < 3) {
                const char* from_name = (from_pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[from_pin_id].c_str() : "UNKNOWN";
                const char* to_name = (to_pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[to_pin_id].c_str() : "UNKNOWN";
                logger.info("[apply_infer_data] Cell delay [%d]'%s' -> [%d]'%s' arc_id=%d: delays=[%.6e,%.6e,%.6e,%.6e] internal, updated %d corners\n",
                    from_pin_id, from_name, to_pin_id, to_name, arc_id,
                    delays[0]*time_to_internal, delays[1]*time_to_internal,
                    delays[2]*time_to_internal, delays[3]*time_to_internal, corners_updated);
            }
            cell_delay_updates++;
            // Do NOT break — GTDatabase creates TWO arcs per Liberty timing arc:
            // Arc_A: timing_arc_id_map[arc*2+0]=valid, [arc*2+1]=-1  (early corner only)
            // Arc_B: timing_arc_id_map[arc*2+0]=-1,    [arc*2+1]=valid (late corner only)
            // Both have the same (from_pin_id, to_pin_id). We must process both so that
            // Arc_A gets early delays (indices 0-3) and Arc_B gets late delays (indices 4-7).
        }

        if (!found) {
            if (cell_delay_missing < 10) {  // Only log first 10 missing
                const char* from_name = (from_pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[from_pin_id].c_str() : "UNKNOWN";
                const char* to_name = (to_pin_id < (int)gtdb.pin_names.size()) ? gtdb.pin_names[to_pin_id].c_str() : "UNKNOWN";
                logger.warning("[apply_infer_data] Could not find cell arc [%d]'%s' -> [%d]'%s' (searched %d fanout arcs)\n",
                    from_pin_id, from_name, to_pin_id, to_name, num_fanout);
            }
            cell_delay_missing++;
        }
    }
    logger.info("[apply_infer_data] Updated %d cell arcs, %d cell delays with no matching arc\n", cell_delay_updates, cell_delay_missing);

    // Copy back to GPU
    cudaMemcpy(arcDelay, h_arcDelay, num_arcs * 8 * sizeof(float), cudaMemcpyHostToDevice);
    logger.info("[apply_infer_data] Copied arcDelay H2D: %d arcs * 8 * 4 bytes\n", num_arcs);

    cudaMemcpy(pinSlew, h_pinSlew, num_pins * 4 * sizeof(float), cudaMemcpyHostToDevice);
    logger.info("[apply_infer_data] Copied pinSlew H2D: %d pins * 4 corners * 4 bytes\n", num_pins);

    // Ensure H2D copy is complete and GPU sees updated data before kernels access it
    cudaDeviceSynchronize();
    logger.info("[apply_infer_data] GPU synchronized after H2D copy - arcDelay and pinSlew ready for kernels\n");

    // Sample verification: read back some values to confirm
    float sample_arcDelay[8];
    if (num_arcs > 0) {
        cudaMemcpy(sample_arcDelay, arcDelay, 8 * sizeof(float), cudaMemcpyDeviceToHost);
        logger.info("[apply_infer_data] Arc 0 after H2D: [%.6e, %.6e, %.6e, %.6e, %.6e, %.6e, %.6e, %.6e]\n",
            sample_arcDelay[0], sample_arcDelay[1], sample_arcDelay[2], sample_arcDelay[3],
            sample_arcDelay[4], sample_arcDelay[5], sample_arcDelay[6], sample_arcDelay[7]);
    }

    float sample_pinSlew[4];
    if (num_pins > 0) {
        cudaMemcpy(sample_pinSlew, pinSlew, 4 * sizeof(float), cudaMemcpyDeviceToHost);
        logger.info("[apply_infer_data] Pin 0 slew after H2D: [%.6e, %.6e, %.6e, %.6e]\n",
            sample_pinSlew[0], sample_pinSlew[1], sample_pinSlew[2], sample_pinSlew[3]);
    }

    // Final sync before returning
    cudaDeviceSynchronize();
    logger.info("[apply_infer_data] GPU synchronized before returning\n");

    delete[] h_arcDelay;
    delete[] h_pinSlew;
}

// ─────────────────────────────────────────────────────────────────────────────
// read_infer: ML inference CSV where node_id == GPUTimer pin_id directly.
// ─────────────────────────────────────────────────────────────────────────────
void GPUTimer::read_infer(const std::string& infile) {
    std::ifstream fin(infile);
    if (!fin.is_open()) {
        logger.error("Cannot open inference file: %s\n", infile.c_str());
        return;
    }
    logger.info("[read_infer] Opened file: %s\n", infile.c_str());

    std::vector<std::pair<int, std::array<float, 4>>> slews, net_delays;
    std::vector<std::tuple<int, int, std::array<float, 4>>> cell_delays;
    float time_to_internal = 1.0f / (gtdb.time_unit * 1e9f);
    logger.info("[read_infer] time_unit=%.6e, time_to_internal=%.6e\n", gtdb.time_unit, time_to_internal);

    std::string line;
    int section = 0;  // 0=none, 1=node, 2=edge
    int line_count = 0;

    while (std::getline(fin, line)) {
        line = trim(line);
        line_count++;
        if (line.empty()) continue;
        if (line.find("# Node predictions") == 0) { section = 1; logger.info("[read_infer] Entering section 1: Node predictions (line %d)\n", line_count); continue; }
        if (line.find("# Cell edge predictions") == 0) { section = 2; logger.info("[read_infer] Entering section 2: Cell edge predictions (line %d)\n", line_count); continue; }
        if (line[0] == '#') continue;

        std::vector<float> values;
        if (section == 1) {
            // node_id, slew_er, slew_ef, slew_lr, slew_lf, net_delay_er, ef, lr, lf
            if (!parse_csv_line(line, values) || values.size() < 9) continue;
            int node_id = static_cast<int>(values[0]);
            std::array<float, 4> slew   = {{values[1], values[2], values[3], values[4]}};
            std::array<float, 4> delays = {{values[5], values[6], values[7], values[8]}};
            slews.push_back({node_id, slew});
            net_delays.push_back({node_id, delays});
            if (slews.size() <= 3 || slews.size() % 10000 == 0)
                logger.info("[read_infer] Node %d: slew=[%.6e,%.6e,%.6e,%.6e] ns, net_delay=[%.6e,%.6e,%.6e,%.6e] ns (total: %zu)\n",
                    node_id, slew[0], slew[1], slew[2], slew[3], delays[0], delays[1], delays[2], delays[3], slews.size());
        } else if (section == 2) {
            // edge_id, from_pin_id, to_pin_id, cell_delay_er, ef, lr, lf
            if (!parse_csv_line(line, values) || values.size() < 7) continue;
            int from_pin_id = static_cast<int>(values[1]);
            int to_pin_id   = static_cast<int>(values[2]);
            std::array<float, 4> delays = {{values[3], values[4], values[5], values[6]}};
            cell_delays.push_back({from_pin_id, to_pin_id, delays});
            if (cell_delays.size() <= 3 || cell_delays.size() % 5000 == 0)
                logger.info("[read_infer] Edge %d: %d->%d, delays=[%.6e,%.6e,%.6e,%.6e] ns (total: %zu)\n",
                    (int)values[0], from_pin_id, to_pin_id, delays[0], delays[1], delays[2], delays[3], cell_delays.size());
        }
    }
    fin.close();
    logger.info("[read_infer] File parsing complete. Parsed %zu slews, %zu net delays, %zu cell delays\n",
                slews.size(), net_delays.size(), cell_delays.size());

    apply_infer_data(slews, net_delays, cell_delays, time_to_internal);

    logger.info("[read_infer] ========== COMPLETE ==========\n");
    logger.info("[read_infer] Loaded inference: %zu slews, %zu net delays, %zu cell delays from %s\n",
                slews.size(), net_delays.size(), cell_delays.size(), infile.c_str());
    logger.info("[read_infer] ================================\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// read_opr_gt_infer: OpenROAD ground-truth CSV where node_id is an OPR-internal
// ID, not a GPUTimer pin ID. Mapping is done via pin_name lookup.
// Also stores GT AT values in host_pinGT_AT for later R² comparison.
// ─────────────────────────────────────────────────────────────────────────────
void GPUTimer::read_opr_gt_infer(const std::string& infile) {
    std::ifstream fin(infile);
    if (!fin.is_open()) {
        logger.error("Cannot open OPR GT infer file: %s\n", infile.c_str());
        return;
    }
    logger.info("[read_opr_gt_infer] Opened file: %s\n", infile.c_str());

    // Build reverse map: pin_name → GPUTimer pin_id
    std::unordered_map<std::string, int> name_to_id;
    name_to_id.reserve(gtdb.pin_names.size());
    for (int i = 0; i < (int)gtdb.pin_names.size(); i++)
        name_to_id[gtdb.pin_names[i]] = i;

    // OPR node_id → GPUTimer pin_id (-1 = unmapped)
    std::unordered_map<int, int> opr_to_gt;

    int num_pins_gt = static_cast<int>(gtdb.pin_names.size());
    host_pinGT_AT.assign(num_pins_gt * 4, std::numeric_limits<float>::quiet_NaN());

    float time_to_internal = 1.0f / (gtdb.time_unit * 1e9f);
    logger.info("[read_opr_gt_infer] time_unit=%.6e, time_to_internal=%.6e\n", gtdb.time_unit, time_to_internal);

    std::vector<std::pair<int, std::array<float, 4>>> slews, net_delays;
    std::vector<std::tuple<int, int, std::array<float, 4>>> cell_delays;

    std::string line;
    int section = 0;
    int line_count = 0, name_miss = 0;

    while (std::getline(fin, line)) {
        line = trim(line);
        line_count++;
        if (line.empty()) continue;
        if (line.find("# Node predictions") == 0) { section = 1; logger.info("[read_opr_gt_infer] Entering section 1: Node predictions (line %d)\n", line_count); continue; }
        if (line.find("# Cell edge predictions") == 0) { section = 2; logger.info("[read_opr_gt_infer] Entering section 2: Cell edge predictions (line %d)\n", line_count); continue; }
        if (line[0] == '#') continue;

        if (section == 1) {
            // node_id, pin_name, gt_at_er, gt_at_ef, gt_at_lr, gt_at_lf,
            // slew_er, slew_ef, slew_lr, slew_lf,
            // net_delay_er, net_delay_ef, net_delay_lr, net_delay_lf  (14 cols)
            auto tokens = split_csv_str(line);
            if (tokens.size() < 14) continue;
            try {
                int opr_id = std::stoi(tokens[0]);
                // OPR uses "hierarchy/inst/pin" separators; GTDatabase uses "hierarchy/inst:pin"
                // Replace only the LAST '/' (which separates instance path from port name).
                std::string pin_name = tokens[1];
                auto slash = pin_name.rfind('/');
                if (slash != std::string::npos) pin_name[slash] = ':';
                auto it = name_to_id.find(pin_name);
                if (it == name_to_id.end()) {
                    opr_to_gt[opr_id] = -1;
                    if (++name_miss <= 5) logger.warning("[read_opr_gt_infer] pin_name '%s' not found in GPUTimer\n", pin_name.c_str());
                    continue;
                }
                int gt_id = it->second;
                opr_to_gt[opr_id] = gt_id;

                // GT AT values (cols 2-5), stored in internal units
                for (int c = 0; c < 4; c++)
                    host_pinGT_AT[gt_id * 4 + c] = std::stof(tokens[2 + c]) * time_to_internal;

                // Slew (cols 6-9) and net delay (cols 10-13)
                std::array<float, 4> slew   = {{std::stof(tokens[6]),  std::stof(tokens[7]),  std::stof(tokens[8]),  std::stof(tokens[9])}};
                std::array<float, 4> delays = {{std::stof(tokens[10]), std::stof(tokens[11]), std::stof(tokens[12]), std::stof(tokens[13])}};
                slews.push_back({gt_id, slew});
                net_delays.push_back({gt_id, delays});

                if (slews.size() <= 3 || slews.size() % 10000 == 0)
                    logger.info("[read_opr_gt_infer] Node opr=%d gt=%d '%s': gt_at=[%.6e,..], slew=[%.6e,..] ns (total: %zu)\n",
                        opr_id, gt_id, pin_name.c_str(), std::stof(tokens[2]), slew[0], slews.size());
            } catch (...) { continue; }

        } else if (section == 2) {
            // edge_id, from_opr_node, to_opr_node, cell_delay_er, ef, lr, lf  (7 cols)
            std::vector<float> values;
            if (!parse_csv_line(line, values) || values.size() < 7) continue;
            int opr_from = static_cast<int>(values[1]);
            int opr_to   = static_cast<int>(values[2]);
            auto it1 = opr_to_gt.find(opr_from), it2 = opr_to_gt.find(opr_to);
            if (it1 == opr_to_gt.end() || it2 == opr_to_gt.end() || it1->second < 0 || it2->second < 0) continue;
            std::array<float, 4> delays = {{values[3], values[4], values[5], values[6]}};
            cell_delays.push_back({it1->second, it2->second, delays});
            if (cell_delays.size() <= 3 || cell_delays.size() % 5000 == 0)
                logger.info("[read_opr_gt_infer] Edge %d: opr %d->%d (gt %d->%d), delays=[%.6e,..] ns (total: %zu)\n",
                    (int)values[0], opr_from, opr_to, it1->second, it2->second, delays[0], cell_delays.size());
        }
    }
    auto device = timing_raw_db.node_size.device();
    timing_raw_db.pinGT_AT = torch::from_blob(host_pinGT_AT.data(), {(long)num_pins, 4}, torch::kFloat32).contiguous().to(device);
    fin.close();
    logger.info("[read_opr_gt_infer] File parsing complete. Parsed %zu slews, %zu net delays, %zu cell delays (%d pin name misses)\n",
                slews.size(), net_delays.size(), cell_delays.size(), name_miss);

    apply_infer_data(slews, net_delays, cell_delays, time_to_internal);

    logger.info("[read_opr_gt_infer] ========== COMPLETE ==========\n");
    logger.info("[read_opr_gt_infer] Loaded: %zu slews, %zu net delays, %zu cell delays from %s\n",
                slews.size(), net_delays.size(), cell_delays.size(), infile.c_str());
    logger.info("[read_opr_gt_infer] ================================\n");
}

}  // namespace gt
