#include "GPUTimer.h"
namespace gt {
void evaluate_sizing_cuda(index_type *level_gate_list,
                          vector<int> level_gate_list_end_cpu,
                          index_type *level_list,
                          vector<int> level_list_end_cpu,
                          index_type *primary_outputs,
                          index_type *topo_order2thread_list_end,
                          index_type *candidate_id2pin_id,
                          index_type *candidate_id2lib_cell_id,
                          index_type *pin_forward_arc_list_end,
                          index_type *pin_forward_arc_list,
                          index_type *pin_backward_arc_list_end,
                          index_type *pin_backward_arc_list,
                          index_type *timing_arc_to_pin_id,
                          index_type *timing_arc_from_pin_id,
                          index_type *arc_types,
                          index_type *pin_id2equivalent_cell_id,
                          int *pin_id2cell_type_id,
                          vector<index_type*> level_equivalent_cell_num_pin,
                          index_type *liberty_cell_type2port_list_end,
                          index_type *liberty_port2timing_list_end,
                          index_type *timing_arc_in_port_id,
                          index_type *pin_id2port_offset_id,
                          float *pinCap,
                          float *pinSlew,
                          float *pinLoad,
                          float *pinRootRes,
                          float *pinRootDelay,
                          float *arcDelay,
                          float *pinAt,
                          float *pinRat,
                          float *POLambda,
                          float *arcLambda,
                          float *level_pinSlew,
                          float *liberty_port_capacitance,
                          float *level_cost,
                          int *level_candidate,
                          int *timing_arc_id_map,
                          GPULutAllocator *d_allocator,
                          float clock_period,
                          int num_pins,
                          int num_arcs,
                          int i,
                          int num_PO
                        );
 
void GPUTimer::evaluate_sizing(int sizing_max_level) {
  // std::cout<<"gate list has " << sizing_level_list_end_cpu.size() << " levels" << std::endl; 
  if(sizing_max_level == -1) sizing_max_level = sizing_level_list_end_cpu.size();
  sizing_max_level = std::min(sizing_max_level, (int)sizing_level_list_end_cpu.size());
  for(int i = 0;i < sizing_max_level; i++)
    evaluate_sizing_cuda(sizing_level_list,
                         sizing_level_list_end_cpu,
                         level_list,
                         level_list_end_cpu,
                         primary_outputs,
                         topo_order2candidate_list_end,
                         candidate_id2pin_id,
                         candidate_id2lib_cell_id,
                         pin_forward_arc_list_end,
                         pin_forward_arc_list,
                         pin_backward_arc_list_end,
                         pin_backward_arc_list,
                         timing_arc_to_pin_id,
                         timing_arc_from_pin_id,
                         arc_types,
                         pin_id2equivalent_cell_id,
                         pin_id2cell_type_id,
                         level_equivalent_cell_num_pin,
                         liberty_cell_type2port_list_end,
                         liberty_port2timing_list_end,
                         timing_arc_in_port_id,
                         pin_id2port_offset_id,
                         pinCap,
                         pinSlew,
                         pinLoad,
                         pinRootRes,
                         pinRootDelay,
                         arcDelay,
                         pinAT,
                         pinRAT,
                         POLambda,
                         arcLambda,
                         level_pinSlew,
                         liberty_port_capacitance,
                         level_cost,
                         level_candidate,
                         timing_arc_id_map,
                         d_allocator, 
                         clock_period,
                         num_pins,
                         num_arcs,
                         i,
                         num_POs);
    // fflush(stdout);

}



}